before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gsl-bin libgsl0-dev
  - sudo apt-get install latexmk
addons:
    apt:
        packages:
            - texlive-full
            - texlive-generic-recommended
            - texlive-latex-recommended
            - texlive-latex-extra
            - texlive-fonts-recommended
            - texlive-fonts-extra
            - texlive-publishers
install:
script:
    - make -C doc/0000-start_paper
after_success: |
    if [[ -n "$GITHUB_API_KEY" ]; then
        git checkout --orphan pdf
        git rm -rf .
        cp doc/0000-start_paper.pdf .
        git add -f 0000-start_paper.pdf
        git -c user.name='travis' -c user.email='travis' commit -m init
        git push -q -f https://drphilmarshall:$GITHUB_API_KEY@github.com/DarkEnergyScienceCollaboration/start_paper pdf
    fi
